from selenium.webdriver.common.by import By

class TestLocators():

 button_skolko_stoit = [By.ID,'accordion__heading-0']
button_hochu_neskolko_samokatov = [By.ID,'accordion__heading-1']
button_kak_raschitivaetsya = [By.ID,'accordion__heading-2']
button_mozhno_li_zakazat = [By.ID,'accordion__heading-3']
button_mozhno_li_prodlit = [By.ID,'accordion__heading-4']
button_vi_privozite_zaryadku = [By.ID,'accordion__heading-5']
button_mozhno_otmenit_zakaz = [By.ID,'accordion__heading-6']
button_i_zhivu_za_mkadom = [By.ID,'accordion__heading-7']
but0 = [By.ID,'accordion__panel-0']
but1 = [By.ID,'accordion__panel-1']
but2 = [By.ID,'accordion__panel-2']
but3 = [By.ID,'accordion__panel-3']
but4 = [By.ID,'accordion__panel-4']
but5 = [By.ID,'accordion__panel-5']
but6 = [By.ID,'accordion__panel-6']
but7 = [By.ID,'accordion__panel-7']
button_order_on_down = [By.XPATH, ".//*[contains(@class, 'Button_Middle__1CSJM')]"]
button_order_on_up = [By.XPATH, ".//*[@class='Button_Button__ra12g']"]
page_order = [By.XPATH,'Order_Header__BZXOb']
field_name = [By.XPATH, ".//*[@placeholder='* Имя']"]
field_surname = [By.XPATH, ".//*[@placeholder='* Фамилия']"]
field_phone_number = [By.XPATH, ".//*[@placeholder='* Телефон: на него позвонит курьер']"]
field_station_tube = [By.XPATH, ".//*[@placeholder='* Станция метро']"]
field_adress = [By.XPATH, ".//*[@placeholder='* Адрес: куда привезти заказ']"]
button_dalee = [By.XPATH, ".//*[text()='Далее']"]
page_order2 = [By.XPATH,'Order_Header__BZXOb']
field_data = [By.XPATH, ".//*[@placeholder='* Когда привезти самокат']"]
field_srok_arenda = [By.XPATH, ".//*[@class='Dropdown-arrow']"]
choose_srok = [By.XPATH,'Dropdown-option is-selected']
dropdown_option = [By.XPATH,'Dropdown-option']
field_cvet_samokata = [By.XPATH,'Checkbox_Label__3wxSf']
button_order_on_second_form_of_order =  [By.XPATH, ".//*[contains(@class, 'Button_Button__ra12g Button_Middle__1CSJM') " "and text()='Заказать']"]
modal_window = [By.XPATH,'Order_ModalHeader__3FDaJ']
button_confirm_on_modal_window = [By.XPATH,'Button_Button__ra12g Button_Middle__1CSJM']
success_modal_window = [By.XPATH, ".//*[@class='Order_ModalHeader__3FDaJ']"]
logo = [By.XPATH, ".//*[@alt='Scooter']"]
main_page = [By.XPATH,'Home_Header__iJKdX']
logo_ya = [By.XPATH, ".//*[@alt='Yandex']"]
new_page = [By.XPATH, ".//iframe[@class='dzen-search-arrow-common__frame' and @aria-label='Поиск Яндекса']"]